name: Code Climate Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-climate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: 988abbd14e2a3e171b344a0fdf0700844064681e
        with:
          coverageCommand: npm run coverage
          debug: true
