name: Code Climate Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  code-climate:
    runs-on: ubuntu-latest
    steps:
      - name: Code Climate Coverage Action
        uses: paambaati/codeclimate-action@v2.7.5
